name: CI - Build & Test

on:
  push:
    branches: [kelvin, main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Dar permissão no mvnw
        run: chmod +x mvnw

      - name: Build
        run: ./mvnw clean package -DskipTests

      - name: Run App
        run: |
          nohup java -jar target/*.jar &
          sleep 15

          - name: Rodar aplicação
        run: |
          chmod +x mvnw
          ./mvnw spring-boot:run &
          sleep 120

      - name: Test Endpoint
        run: |
          curl --fail http://localhost:8080 || exit 1